# Generated by Django 3.2.9 on 2022-01-14 04:15

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={},
        ),
        migrations.RemoveField(
            model_name='user',
            name='email',
        ),
        migrations.AddField(
            model_name='user',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='Баланс'),
        ),
        migrations.AddField(
            model_name='user',
            name='car',
            field=models.CharField(blank=True, default='', max_length=32, null=True, verbose_name='Машина'),
        ),
        migrations.AddField(
            model_name='user',
            name='middle_name',
            field=models.CharField(blank=True, default='', max_length=32, null=True, verbose_name='Отчество'),
        ),
        migrations.AddField(
            model_name='user',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField(default='', help_text='Пример, +79510549236', max_length=128, region=None, unique=True, verbose_name='Номер телефона'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('Клиент', 'Client'), ('Администратор', 'Administrator'), ('Механик', 'Mechanic')], default='Клиент', max_length=13, verbose_name='Роль'),
            preserve_default=False,
        ),
    ]
