# Generated by Django 3.2.9 on 2022-01-14 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_user_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('Клиент', 'Client'), ('Администратор', 'Administrator'), ('Механик', 'Mechanic')], default='Клиент', max_length=13, verbose_name='Роль'),
        ),
    ]
